server:
  port: 8080
spring:
  datasource:
    url: jdbc:mysql://${DB_HOST}:${DB_PORT}/${DB_NAME}
    driverClassName: com.mysql.cj.jdbc.Driver
    username: ${DB_USER}
    password: ${DB_PASSWORD}

mybatis:
  config-location: classpath:mybatis-config.xml

jwt:
  secret: ${SECRET_KEY}
  refreshTokenValidity: ${REFRESH_TOKEN}
  accessTokenValidity: ${ACCESS_TOKEN}

cloud:
  aws:
    credentials:
      accessKey: ${CLOUD_ACCESS_KEY}
      secretKey: ${CLOUD_SECRET_KEY}
    s3:
      bucket: sound-hub
    region:
      static: ap-northeast-2
      auto: false
    stack:
      auto: false

logging:
  level:
    root: debug